import type { AppProps } from 'next/app';
import '../styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}
